### ISSUE TITLE
如果是像分析app用了什么库，有什么好的方案么

### ISSUE THREAD

**Issue by kaleai** [fengzhizi715/AnalysisApp#1]

**Comment by fengzhizi715** [comment]
我会把它放到roadmap里 ：）

**Comment by fengzhizi715** [comment]
@tianzhijiexian 我会把它放到roadmap里 ：）

**Comment by kaleai** [comment]
可以说下怎么实现的么，看到有人分析使用rxjava库的app，不知道是怎么分析出来的。

**Comment by fengzhizi715** [comment]
@tianzhijiexian  谷歌有一个库，可以分析应用的技术框架和开源库
https://github.com/google/android-classyshark

可以看下这篇文章：http://www.jianshu.com/p/8e8b88ea2197
